version: '3.8'

services:
  api:
    build: ./backendWS
    restart: unless-stopped
  web:
    build: ./tag-cloud
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    ports:
      - '5000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Настройки Nginx
      #- ./tag-cloud/dist:/usr/share/nginx/html # Статические файлы Vue приложения
    depends_on:
      - api
      - web
