version: '3.8'

services:
  api:
    build: ./backendWS
    restart: unless-stopped
    depends_on:
      - db

  web:
    build: ./tag-cloud
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - '5341:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Настройки Nginx
      #- ./tag-cloud/dist:/usr/share/nginx/html # Статические файлы Vue приложения
    depends_on:
      - api
      - web

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: cloudtags
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
